# 配置文件

win_width = 800 # 窗口宽 建议微调，不然影响鼠标点击
win_height = 1600 # 窗口高 建议微调，不然影响鼠标点击

character_json = 'Character\llny\llny.json' # 角色卡路径

device = 'cuda' # 'cuda'即GPU运行模型;'cpu'字面意思;如果指定显卡，可以是'cuda:1'

context_length = 5 # 上下文长度
save_memory_steps = 2 # 几条对话进行一次记忆保存
memory_top_k = 3 # 返回记忆的最大长度
memory_similarity_threshold = 0.5 # 记忆相似度阈值

# 小牛翻译 选填 默认用内置免费api 用内置免费api可能会导致字幕显示异常
niutrans_app_id = ''
niutrans_api_key = ''

mixanimator_wait = 0 # -1即关闭MixAnimator，大于等于0以上即MixAnimator播放等待时间
mixanimator_weight = [1, 3, 2, 1, 2, 1, 1, 2] # 各随机动画的播放权重
mixanimator_max_sample = 3 # 动画最大组合数量

your_voice = '' # 说话人确认参考音频 这里输入你的声音音频路径
verifier_threshold = 0.2 # 说话人确认阈值
aggressiveness = 3 # VAD检测人声敏感度 1最敏感 3最不敏感
shot_word = ['看一下', '看看这是啥', '识别一下', '你看到了啥'] # 屏幕识别口令 非多模态模型无法使用
hot_word = "{'蔡徐坤':['']}" # 热词替换 将ASR识别不出来的单词进行替换

tts_api2 = "http://127.0.0.1:9880/tts" # GPTSovits的apiv2网址
cut_length = 10 # TTS文本最小切片长度 合适的长度可以有效降低首个响应时间，不宜太小或太大

# --> 必填!!! <--
["required"]
base_url = ''
api_key = ''
chat_model = ''
temperature = 1.0
top_p = 0.9
max_tokens = 16384
max_pixels = 50176

# 辅助型大模型api 选填 默认用内置免费api
["auxiliary"]
base_url = ''
api_key = ''
chat_model = ''