# 配置文件
user_name = '' # 用户名 必填
character_toml = 'Character\拉菲\拉菲.toml' # 角色卡路径

device = 'cuda' # 'cuda'即GPU运行模型;'cpu'字面意思;如果指定显卡，可以是'cuda:1'

context_length = 10000 # 上下文长度
save_memory_steps = 2 # 几条对话进行一次记忆保存
memory_top_k = 5 # 返回记忆的最大长度
memory_similarity_threshold = 0.1 # 记忆相似度阈值
conversations_length = 1000

# 小牛翻译 选填 默认用内置免费api
niutrans_app_id = ''
niutrans_api_key = ''

your_voice = '' # 声纹识别参考音频 这里输入你的人声音频路径
verifier_threshold = 0.2 # 声纹识别阈值
aggressiveness = 3 # VAD检测人声敏感度 1最敏感 3最不敏感
shot_word = ['看', '屏幕'] # 屏幕识别触发关键词 非多模态模型无法使用
hot_word = "{'蔡徐坤':[]}" # 热词替换 将ASR识别不出来的单词进行替换

gsv_api2 = "http://127.0.0.1:9880/tts" # GPTSovits的apiv2网址
kokoro_api = "http://127.0.0.1:8880/v1"
rvc_url = "http://127.0.0.1:7897"
cut_length = 10 # TTS文本最小切片长度 合适的长度可以有效降低首个响应时间，不宜太小或太大

input_box = true # 是否启用输入框
always_screenshot = false # 是否每次对话都识别屏幕
initiative_wait_range = [2, 30] # 主动对话间隔范围(单位为分钟)，赋值'none'字符串即关闭主动对话
exp_fadeout = 3 # 表情消失时间

# --> 必填!!! <--
["required"]
base_url = ''
api_key = ''
chat_model = ''
temperature = 1.0
top_p = 0.9
max_tokens = 16384
max_pixels = 50176

# 辅助型大模型api 必填
["auxiliary"]
base_url = ''
api_key = ''
chat_model = ''

["modelscope"]
base_url = 'https://api-inference.modelscope.cn/v1/'
api_key = ''

# www.bing.com的cookie，请自行替换
www_bing_cookie = ""

# cn.bing.com的cookie，请自行替换
cn_bing_cookie = ""

search_max_context = 30000 # 网页返回的最大文本长度
search_pages = 2 # 搜索引擎返回页数
headless = false # 游览器无头模式（即Agent调用游览器时，是否不弹窗）
has_proxy = false # 电脑是否开启了代理（vpn）

agent_event = true


port = 8080 # 端口（如没有占用端口，则不要改动）
